### ISSUE TITLE
Terminal theme

### ISSUE THREAD

**Issue by jbrooksuk** [visionmedia/stack#11]
Off topic, I know. But would you mind sharing your Terminal theme?

**Comment by danielhusar** [comment]
+1 :)

**Comment by jbrooksuk** [comment]
@visionmedia is this something you'd mind sharing with us? Your whole Terminal setup looks very nice!

**Comment by tj** [comment]
it's just the default "Slate" theme haha, I switch between it and the default white one depending on contrast, I still like white a lot

**Comment by jbrooksuk** [comment]
I'm not seeing a Slate theme in the preferences, or is it a Yosemite thing?

**Comment by tj** [comment]
hmmm must be! maybe I got it somewhere else but I don't remember doing that

**Comment by jbrooksuk** [comment]
Any chance you could export it for us, please? :)

**Comment by tj** [comment]
no time right now but maybe later!

**Comment by jbrooksuk** [comment]
Cheers!

**Comment by jbrooksuk** [comment]
It's not a Yosemite theme by the way, so whenever you get a minute, that'd be great :)

**Comment by tj** [comment]
weird! here it is https://dl.dropboxusercontent.com/u/6396913/misc/slate.terminal

**Comment by ruimarinho** [comment]
@visionmedia I hope you don't mind me sharing a port of the theme for iTerm2. I really like it too, thanks! :-)

http://cl.ly/0H3627262e2f
