### ISSUE TITLE
How do you change the tty line on the fly from state pending to complete ? 

### ISSUE THREAD

**Issue by first-developer** [visionmedia/stack#22]
Hi,
First, thank for this cool tool :+1: . However, what's I find more interesting, is the way you rewrite the command line without appending to stdout. It looks like you re able to make something like stdout.replaceLine(...) ^^. 
Could you please explain me how you do this? what package are involved ? I look into your code and what I have noticed is that the `pacakge interractive` is use to display the spin : 

```
// Log running of commit.
func (l *Logger) Start(arg, commit string) {
    s := spin.New()
        ...
            case <-time.Tick(100 * time.Millisecond):
                fmt.Fprintf(l.w, "\r\033[36m %s %s\033[0m %s ", s.Next(), shorten(commit), arg)
                s.Next()
            }
        ...
}

```

And the package main use method `hide()` and `show()` to do something :) .

Thanks in advance

**Comment by lithammer** [comment]
I believe the trick is `\r` at the beginning of the `fmt.Fprintf` function. Try this for example:

``` go
package main

import (
    "fmt"
    "time"
)

func main() {
    ticker := time.Tick(time.Second)
    for i := 1; i <= 10; i++ {
        <-ticker
        fmt.Printf("\r %d/10", i)
    }
}
```

**Comment by tj** [comment]
^ yup

**Comment by first-developer** [comment]
Thanks it works :) @renstrom 
But what is the point of the `show()` and `hide()` behaviour ?

**Comment by tj** [comment]
those just toggle the cursor display

**Comment by first-developer** [comment]
Ok again thanks ! 
You rock dudes ( @renstrom & @tj  ) :+1:
